"""Configuration for the UR3e hoop robot."""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg


UR3E_ARM_JOINTS = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

UR3E_EFFORT_LIMITS_NM = {
    "shoulder_pan_joint": 56.0,
    "shoulder_lift_joint": 56.0,
    "elbow_joint": 28.0,
    "wrist_1_joint": 12.0,
    "wrist_2_joint": 12.0,
    "wrist_3_joint": 12.0,
}

UR3E_NOMINAL_VELOCITY_LIMITS_RAD_S = {
    "shoulder_pan_joint": 3.1416,
    "shoulder_lift_joint": 3.1416,
    "elbow_joint": 3.1416,
    "wrist_1_joint": 6.2832,
    "wrist_2_joint": 6.2832,
    "wrist_3_joint": 6.2832,
}


def _find_usd_asset(filename: str) -> str:
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "USD_File" / filename
        if candidate.is_file():
            return str(candidate)
    raise FileNotFoundError(f"Unable to find USD_File/{filename} from {__file__}")


UR3E_HOOP_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=_find_usd_asset("UR-with-gripper.usd"),
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            rigid_body_enabled=True,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=5.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        joint_pos={
            "shoulder_pan_joint": 0.0,
            "shoulder_lift_joint": -1.57,
            "elbow_joint": 0.0,
            "wrist_1_joint": -1.57,
            "wrist_2_joint": 0.0,
            "wrist_3_joint": 0.0,
        },
    ),
    actuators={
        "arm": ImplicitActuatorCfg(
            joint_names_expr=UR3E_ARM_JOINTS,
            effort_limit_sim=UR3E_EFFORT_LIMITS_NM,
            velocity_limit_sim=UR3E_NOMINAL_VELOCITY_LIMITS_RAD_S,
            stiffness=800.0,
            damping=40.0,
        ),
    },
)

# Left-hand variant: same robot with the Hoop prim rotated 180 deg about the
# wrist_3 Z axis (disk offset +0.5 m on X instead of -0.5 m). Generated by
# scripts/make_left_hand_usd.py from UR-with-gripper.usd.
UR3E_HOOP_LEFT_CFG = UR3E_HOOP_CFG.replace(
    spawn=UR3E_HOOP_CFG.spawn.replace(
        usd_path=_find_usd_asset("UR-with-gripper-left.usd"),
    ),
)

# Backward-compatible name used by older configs/imports.
UR_GRIPPER_CFG = UR3E_HOOP_CFG
