#!/usr/bin/env python3
"""Check rollout joint targets against metadata safety limits."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


JOINT_NAMES = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate rollout joint_position_target_rad against UR3e sim-to-real safety metadata."
    )
    parser.add_argument("--rollout", required=True, help="rollouts_*_episodes.json generated by scripts/skrl/play.py")
    parser.add_argument(
        "--position-margin",
        type=float,
        default=1.0e-6,
        help="Allowed position-limit margin in radians.",
    )
    parser.add_argument(
        "--velocity-margin",
        type=float,
        default=1.0e-6,
        help="Allowed velocity-limit margin in rad/s.",
    )
    parser.add_argument(
        "--acceleration-margin",
        type=float,
        default=1.0e-6,
        help="Allowed acceleration-limit margin in rad/s^2.",
    )
    return parser.parse_args()


def _load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as file:
        payload = json.load(file)
    if not isinstance(payload, dict):
        raise SystemExit(f"Rollout root must be an object: {path}")
    return payload


def _vector(metadata: dict[str, Any], key: str) -> list[float]:
    value = metadata.get(key)
    if not isinstance(value, list) or len(value) != 6:
        raise SystemExit(f"metadata.{key} must be a 6-element list")
    return [float(item) for item in value]


def _target(sample: dict[str, Any], episode_index: int, sample_index: int) -> list[float]:
    value = sample.get("joint_position_target_rad")
    if not isinstance(value, list) or len(value) != 6:
        raise SystemExit(f"episode {episode_index} sample {sample_index}: joint_position_target_rad must have length 6")
    return [float(item) for item in value]


def _before(sample: dict[str, Any]) -> list[float] | None:
    value = sample.get("joint_position_before_rad")
    if not isinstance(value, list) or len(value) != 6:
        return None
    return [float(item) for item in value]


def _update_max(values: list[float], candidate: list[float]) -> None:
    for index, item in enumerate(candidate):
        values[index] = max(values[index], abs(item))


def main() -> None:
    args = _parse_args()
    rollout_path = Path(args.rollout).expanduser().resolve()
    payload = _load_json(rollout_path)
    metadata = payload.get("metadata")
    if not isinstance(metadata, dict):
        raise SystemExit("rollout metadata object is required")

    dt = float(metadata.get("dt_s", 0.0) or 0.0)
    if dt <= 0.0:
        raise SystemExit("metadata.dt_s must be positive")
    if metadata.get("joint_names") != JOINT_NAMES:
        raise SystemExit("metadata.joint_names/order does not match the UR3e arm contract")

    lower = _vector(metadata, "joint_position_lower_rad")
    upper = _vector(metadata, "joint_position_upper_rad")
    velocity_limit = _vector(metadata, "joint_velocity_safe_rad_s")
    acceleration_limit = _vector(metadata, "joint_acceleration_safe_rad_s2")

    episodes = payload.get("episodes")
    if not isinstance(episodes, list) or not episodes:
        raise SystemExit("rollout must contain at least one episode")

    violations: list[str] = []
    max_abs_velocity = [0.0] * 6
    max_abs_acceleration = [0.0] * 6
    max_position_margin_used = [0.0] * 6
    samples_checked = 0

    for episode_index, episode in enumerate(episodes):
        samples = episode.get("samples") if isinstance(episode, dict) else None
        if not isinstance(samples, list) or not samples:
            violations.append(f"episode {episode_index}: no samples")
            continue

        previous_target: list[float] | None = None
        previous_velocity: list[float] | None = None
        for sample_index, sample in enumerate(samples):
            if not isinstance(sample, dict):
                violations.append(f"episode {episode_index} sample {sample_index}: sample is not an object")
                continue
            target = _target(sample, episode_index, sample_index)
            before = _before(sample)

            for joint_index, position in enumerate(target):
                lower_over = lower[joint_index] - position
                upper_over = position - upper[joint_index]
                margin_used = max(lower_over, upper_over, 0.0)
                max_position_margin_used[joint_index] = max(max_position_margin_used[joint_index], margin_used)
                if lower_over > args.position_margin or upper_over > args.position_margin:
                    violations.append(
                        f"episode {episode_index} sample {sample_index} {JOINT_NAMES[joint_index]}: "
                        f"target {position:.6f} rad outside [{lower[joint_index]:.6f}, {upper[joint_index]:.6f}]"
                    )

            velocity: list[float] | None = None
            if previous_target is not None:
                velocity = [(target[index] - previous_target[index]) / dt for index in range(6)]
            elif before is not None:
                velocity = [(target[index] - before[index]) / dt for index in range(6)]

            if velocity is not None:
                _update_max(max_abs_velocity, velocity)
                for joint_index, value in enumerate(velocity):
                    if abs(value) > velocity_limit[joint_index] + args.velocity_margin:
                        violations.append(
                            f"episode {episode_index} sample {sample_index} {JOINT_NAMES[joint_index]}: "
                            f"estimated velocity {value:.6f} rad/s exceeds {velocity_limit[joint_index]:.6f}"
                        )

            if velocity is not None and previous_velocity is not None:
                acceleration = [(velocity[index] - previous_velocity[index]) / dt for index in range(6)]
                _update_max(max_abs_acceleration, acceleration)
                for joint_index, value in enumerate(acceleration):
                    if abs(value) > acceleration_limit[joint_index] + args.acceleration_margin:
                        violations.append(
                            f"episode {episode_index} sample {sample_index} {JOINT_NAMES[joint_index]}: "
                            f"estimated acceleration {value:.6f} rad/s^2 exceeds {acceleration_limit[joint_index]:.6f}"
                        )

            previous_target = target
            if velocity is not None:
                previous_velocity = velocity
            samples_checked += 1

    print(f"Rollout safety summary: {rollout_path}")
    print(f"samples_checked: {samples_checked}")
    print("max_abs_velocity_rad_s:")
    for name, value, limit in zip(JOINT_NAMES, max_abs_velocity, velocity_limit, strict=True):
        ratio = value / limit if limit > 0.0 else math.inf
        print(f"  {name}: {value:.6f} / {limit:.6f} ({ratio:.2f}x)")
    print("max_abs_acceleration_rad_s2:")
    for name, value, limit in zip(JOINT_NAMES, max_abs_acceleration, acceleration_limit, strict=True):
        ratio = value / limit if limit > 0.0 else math.inf
        print(f"  {name}: {value:.6f} / {limit:.6f} ({ratio:.2f}x)")

    if violations:
        print("\nRollout safety validation FAILED")
        for violation in violations[:100]:
            print(f"- {violation}")
        if len(violations) > 100:
            print(f"- ... {len(violations) - 100} additional violation(s)")
        raise SystemExit(1)

    print("\nRollout safety validation OK")


if __name__ == "__main__":
    main()
